### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by yograjyog** [daolamgit/Predaq#1]
Dear Dao Lam, 

Is there any way that i can use this for the VMAT plans? I am novice in learning the python. I will appreciate if you can tell me how to run this script in detail. Thanks in advance.

**Comment by daolamgit** [comment]
Hi Yoga,
I just updated the README with more details. Once you install Anaconda, make sure Anaconda is in your SYSTEM PATH, then you can just type **python plan_complexity.py -i** full_path_of_your_plan_file **-o** full_path_of_your_result
